### ISSUE TITLE
EPA logo appears over menu options in IE (v11)

### ISSUE THREAD

**Issue by diliniabey** [ICFI/epa-eds#18]
The EPA logo appears over the menu options on the left when using IE version 11.

![image](https://cloud.githubusercontent.com/assets/16403687/11960914/0b4dd6d4-a8a3-11e5-8fb5-5f4013cfc429.png)

**Comment by ptisdel** [comment]
how is this after the latest update?

**Comment by diliniabey** [comment]
Fixed
