### ISSUE TITLE
Move hand image further to the right

### ISSUE THREAD

**Issue by diliniabey** [ICFI/epa-eds#21]
The hand graphic on Climate Action page needs to be moved further to the right, to match/align with the plug graphic on Power Producers page.

![image](https://cloud.githubusercontent.com/assets/16403687/11962177/d25f6bfe-a8ab-11e5-8944-d007c4ddbaa5.png)

**Comment by ptisdel** [comment]
fixed; check again after next revision

**Comment by diliniabey** [comment]
Fixed.
