### ISSUE TITLE
Accessibility check - Image alt tags

### ISSUE THREAD

**Issue by jvanderlan** [ICFI/epa-eds#22]
Alt tags needed for images across application

List per source code:

Line #51 - &lt;img id="sidebarEPALogo" src='images/sidebar/epa-seal.png'/>
Line #62 - &lt;div id="header">&lt;img id="headerLogo" src="images/top-epa-logo.png"/></div>
Line #71 - &lt;img src="images/home/hand-with-plant.png"/>
Line #146 - &lt;img id="bluePlug" src="images/power/blue-plug.png"/>
Line #147 - &lt;img id="donutChart" src="images/power/donut-chart.png"/>
Line #183 -  &lt;img src="images/power/big-powerplant-icon.png"/>
Line #197 - &lt;img src="images/power/gas-pump-icon.png"/>
Line #206 - &lt;img src="images/power/vehicle-icon.png"/>
Line #215 - &lt;img src="images/power/coal-plant-icon.png"/>

**Comment by ptisdel** [comment]
this is complete!
