### ISSUE TITLE
Menu should be closed by default on Home page load?

### ISSUE THREAD

**Issue by szieglerICF** [ICFI/epa-eds#28]
Opened the site on my iPhone 6. With the menu defaulted to open, it covers a lot of the content.

![2015-12-22 13 56 59](https://cloud.githubusercontent.com/assets/11738877/11963322/17ca19de-a8b4-11e5-932c-d074267c1091.png)

**Comment by ptisdel** [comment]
closed by default on screens smaller than 900px wide now - look for this change in the next push

**Comment by szieglerICF** [comment]
Looks good!
