### ISSUE TITLE
Responsive: Donut chart cut off in 320x480 and 360x640

### ISSUE THREAD

**Issue by diliniabey** [ICFI/epa-eds#41]
The donut chart is cut off and the text next to it cannot be seen

![image](https://cloud.githubusercontent.com/assets/16403687/11965569/54a322a6-a8c3-11e5-898f-b4611607ab19.png)

![image](https://cloud.githubusercontent.com/assets/16403687/11965587/7fc3ad70-a8c3-11e5-8619-24065fce5364.png)

**Comment by ptisdel** [comment]
fixed this, check last push

**Comment by diliniabey** [comment]
Fixed
