### ISSUE TITLE
Responsive: State selection box in the Power Plant page is not usable in 320x480 and 360x640 

### ISSUE THREAD

**Issue by diliniabey** [ICFI/epa-eds#43]
State selection box in the Power Plant page is pushed together. The content of the boxed are can't be read and the state dropdown is not usable.

![image](https://cloud.githubusercontent.com/assets/16403687/11965698/53f16ca4-a8c4-11e5-99bd-25f66406b880.png)
![image](https://cloud.githubusercontent.com/assets/16403687/11965701/59900986-a8c4-11e5-9915-04b5df48120f.png)

**Comment by ptisdel** [comment]
fixed! check on latest push

**Comment by diliniabey** [comment]
Fixed
